/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:4af17b0e-bcd4-4c39-b889-116629445cf2",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_SPMqeoEFa",
    "aws_user_pools_web_client_id": "6rqn0o23rkp40b0nvm5qimlsuh",
    "oauth": {}
};


export default awsmobile;
